spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://host.docker.internal:3306/uccenter
server:
  servlet:
    context-path: /
  port: 8080
